act reg mar 9 nov 21 19:42

diff --git a/.local/bin/menu-programas b/.local/bin/menu-programas
--- a/.local/bin/menu-programas
+++ b/.local/bin/menu-programas
@@ -1,16 +1,44 @@
-#!/bin/sh
+#!/usr/bin/sh
 
-#Lanzador de programas .desktop para Dmenu, puede ser ajustado para rofi.
-DESKTOP_FILES="$(du -ha /usr/share/applications/ | grep .desktop | awk '{print $2}')"
-declare -A HASHMAP
-for FILE in $DESKTOP_FILES
-do
-        APP_NAME="$(cat $FILE | grep Name= | sed 's/Name=//g' | head -1)"
-        if [ "$APP_NAME" == "" ]; then
-            APP_NAME="$(sed 's/\/usr\/share\/applications\//$FILE/g')"
-        fi
-        HASHMAP["$APP_NAME"]=$FILE
-done
-SELECTION=$(printf "%s\n" "${!HASHMAP[@]}" | dmenu -l 5 -fn "SF\\Compact\\Display-10" -p "Menu-Desk:")
-gtk-launch "$(echo ${HASHMAP[$SELECTION]} | sed 's/\/usr\/share\/applications\///g')"
-exit
+# parses known locations for .desktop files
+# written by Nathaniel Maia, June 2018
+
+# associative array to store paths as basename values
+declare -A PATHS
+
+# check we have required software
+if ! hash awk find grep dmenu &>/dev/null; then
+    echo -e "ERROR: This script requires: awk find grep dmenu" && exit 1
+fi
+
+main() {
+    # base file name storage
+    local names=""
+    while read -r f; do
+        n="$(basename "$f" | awk -F'.' '{print $1}')"
+        names="$names
+$n"
+        PATHS["$n"]="$f"
+    done <<< "$(find -L /usr/share/applications/ -type f -name '*.desktop' | sort -r)"
+
+    local ans="$(dmenu -l 5 -fn "Iosevka-9" -p .Desktop: "$@" <<< "$names")"
+    [[ $? != 1 && -n $ans ]] && run "$ans" || return 1
+}
+
+run() {
+    local cmd
+    cmd="$(grep '^Exec' "${PATHS["$1"]}")"
+    cmd="${cmd/Exec=/}"
+    cmd="${cmd/ %*/}"
+    echo -e "$cmd"
+    { [[ $cmd ]] && "$cmd" || return 1; }
+    if [[ $? != 0 ]]; then
+        echo "ERROR: Something went wrong when trying to run: $cmd"
+        return 1
+    fi
+    return 0
+}
+
+main "$@" &
+
+exit 0
